//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPedidosItems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPedido
    {
        public int CodigoItem { get; set; }
        public int CodigoPedido { get; set; }
        public string Nombre { get; set; }
        public int Cantidad { get; set; }
        public int Precio { get; set; }
    
        public virtual Pedido Pedido { get; set; }
    }
}
